module.exports = [
    '<div>',
    '<div class="route-page__body-feed__card raised">',
    '<div class="card-main">',
    '<div class="card-main__inner trip-card">',
    '<div class="trip-card__body">',
    '<div class="card-main__inner-city card-main__inner-city_departure">',
    '<span class="city-name">{{departure.cityName}}</span>',
    '<span class="station-name">{{departure.stationName}}</span>',
    '</div>',
    '<div class="card-main__inner-points">',
    '<div class="trip-card__time-cell-wrap">',
    '<span class="trip-card__time-cell-label">отправление</span>',
    '<div class="trip-card__time-cell">',
    '<span class="trip-card__time-cell-time">{{departure.time}}</span>',
    '<span class="trip-card__time-cell-date">{{departureDateString}}</span>',
    '</div>',
    '</div>',
    '<div class="trip-card__duration-cell">',
    '<span class="trip-card__duration-cell-label">в пути</span>',
    '<span class="trip-card__duration-cell-value">{{totaltime}}</span>',
    '</div>',
    '<div class="trip-card__time-cell-wrap">',
    '<span class="trip-card__time-cell-label">прибытие</span>',
    '<div class="trip-card__time-cell">',
    '<span class="trip-card__time-cell-time">{{arrival.time}}</span>',
    '<span class="trip-card__time-cell-date">{{arrivalDateString}}</span>',
    '</div>',
    '</div>',
    '</div>',
    '<div class="card-main__inner-city card-main__inner-city_arrival">',
    '<span class="city-name accent-color">{{arrival.cityName}}</span>',
    '<span class="station-name">{{arrival.stationName}}</span>',
    '</div>',
    '<div class="trip-card__body-footer">',
    '<span class="trip-card__body-footer-bus">Перевозчик: {{carrier}},  Автобус: {{bus.model}}, год выпуска: {{bus.manufactureDate}}</span>',
    '<span class="trip-card__body-footer-icons">',
    '</span></div></div>',
    '<div class="trip-card__details">',
    '<div class="trip-card__adult-price">',
    '<span class="trip-card__adult-price-value">{{adultPrice}}<b class="ruble">₽</b></span>',
    '<span class="trip-card__adult-price-label">за взрослый билет</span>',
    '</div>',
    '<div class="trip-card__seats-info"><span>свободно {{freeSeats}} мест</span></div>',
    '<div class="trip-card__action"><div style="color: rgba(0, 0, 0, 0.87); background-color: rgb(255, 255, 255); transition: all 450ms cubic-bezier(0.23, 1, 0.32, 1) 0ms; box-sizing: border-box; font-family: Roboto, sans-serif; -webkit-tap-highlight-color: rgba(0, 0, 0, 0); box-shadow: rgba(0, 0, 0, 0.12) 0px 1px 6px, rgba(0, 0, 0, 0.12) 0px 1px 4px; border-radius: 2px; display: inline-block; min-width: 88px; width: 100%;">',
    '<button tabindex="0" type="button" style="border: 10px; box-sizing: border-box; display: inline-block; font-family: Roboto, sans-serif; -webkit-tap-highlight-color: rgba(0, 0, 0, 0); cursor: pointer; text-decoration: none; margin: 0px; padding: 0px; outline: none; font-size: inherit; font-weight: inherit; position: relative; z-index: 1; height: 36px; line-height: 36px; width: 100%; border-radius: 2px; transition: all 450ms cubic-bezier(0.23, 1, 0.32, 1) 0ms; background-color: rgb(243, 246, 247); text-align: center;"><div><div style="height: 36px; border-radius: 2px; transition: all 450ms cubic-bezier(0.23, 1, 0.32, 1) 0ms; top: 0px;"><span style="position: relative; opacity: 1; font-size: 14px; letter-spacing: 0px; text-transform: uppercase; font-weight: 500; margin: 0px; user-select: none; padding-left: 16px; padding-right: 16px; color: rgba(0, 0, 0, 0.87);">Забронировать</span></div></div></button>',
    '</div></div></div></div></div></div>',
    '</div>'
]
